/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:1ff2d0c3b3f604cc1c43bd11b48af98e:32bde4a0bcb1e367f4e2a9042398dc3f:a08b0a717d83589f7c8d330c4ce954d8$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class dropsRD
	{
		public const string AcidDrop = "acidDrop";
		public const string AlkDrop = "alkDrop";
		public const string GoldDrop = "goldDrop";
		public const string RainDrop = "rainDrop";
	}
}